steps:
- id: 'Install dependencies'
  name: 'gcr.io/cloud-builders/npm'
  args: ['install', '-qy']
  dir: 'client'
- id: 'Testing'
  name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'test']
  dir: 'client'
  env:
  - 'CI=true'
- id: 'Container creation'
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/web:$TAG_NAME', '-f', 'Dockerfile.prod', '.']
  dir: 'client'
images: ['gcr.io/$PROJECT_ID/web:$TAG_NAME']
timeout: '1600s'
tags: ['web']
