FROM node:10.10-alpine as client

WORKDIR /app
COPY package*.json ./
RUN npm install -qy
COPY . .
RUN npm run build

# Setup the nginx server
FROM nginx:1.14-alpine

WORKDIR /app
COPY --from=client /app/build/ /usr/share/nginx/html

WORKDIR /app/server/
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
