version: "3"
services:
  graphql:
    build:
      context: ./server/
      dockerfile: Dockerfile.prod
    command: npm start
    ports:
      - "3030:3030"
    restart: always
    env_file: ./server/.production.env

  web:
    build: .
    ports:
      - "80:80"
    restart: always
    env_file: ./client/.production.env
