version: "3"
services:
  graphql:
    build:
      context: ./server/
      dockerfile: Dockerfile.prod
    ports:
      - "3030:3030"
    restart: always

  web:
    build: .
    ports:
      - "80:80"
    restart: always
