version: "3"
services:
  mongo1:
    image: mongo
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--quiet", "--replSet", "rs", "--bind_ip_all"]

  mongosetup:
    image: mongo
    volumes:
      - ./scripts:/scripts
    restart: always
    depends_on:
      - mongo1
    entrypoint: [ "bash", "/scripts/setupreplica.sh" ]

  graphql:
    build: .
    command: npm run dev
    volumes:
      - .:/app/
      - /app/node_modules
    ports:
      - "3030:3030"
    depends_on:
      - mongosetup
    environment:
      PORT: 3030
      NODE_ENV: development
      MONGO_URI: mongodb://mongo1:27017/yoledger-dev?replicaSet=rs
  web:
    build:
      context: ./client/
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - graphql
    environment:
      REACT_APP_GRAPHQL_ENDPOINT: http://graphql:3030/graphql
