version: "3"
services:
  mongo1:
    image: mongo
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--quiet", "--replSet", "rs", "--bind_ip_all"]

  mongosetup:
    image: mongo
    volumes:
      - ./scripts:/scripts
    restart: always
    depends_on:
      - mongo1
    entrypoint: [ "bash", "/scripts/setupreplica.sh" ]
