steps:
- id: 'Package installation'
  name: 'gcr.io/cloud-builders/npm'
  args: ['install', '-qy']
  dir: 'server'
# - id: 'Model testing'
#   name: 'gcr.io/cloud-builders/npm'
#   args: ['run', 'test:model-lh']
#   dir: './server'
- id: 'GraphQL testing'
  name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'test:gql']
  dir: 'server'
- id: 'Container creation'
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/api:$TAG_NAME', '-f', 'Dockerfile.prod', '.']
  dir: 'server'
images: ['gcr.io/$PROJECT_ID/api:$TAG_NAME']
timeout: '1600s'
tags: ['api']
